### ISSUE TITLE
Tehenhauin's missions are completed even if you don't meet the requirements

### ISSUE THREAD

**Issue by EnderBen** [chadvandy/cbfm_wh3#1068]
**Describe the bug**
Tehenhauin's missions in the Prophecy of Sotek complete too soon. It doesn't seem too bad, but I've had campaigns break when it reverses itself on turn 40 and then can never be completed. 

**To Reproduce**
1. Play as Tehenhauin
2. Attack settlement Sentinel of Time (this might not be the only way to trigger this but it does for me almost always). 
3. When battle ends will complete mission to "Own the entirety of 2 provinces. (Current total 4)" Even though I only own 1 province completely. See screenshot. 

**Screenshots**
![20230607145608_1](https://github.com/chadvandy/cbfm_wh3/assets/115371548/6e98191f-c830-4cd2-bb3a-81ddf03db489)

**Saves**
[Cult of Sotek_Quick Save.72207066769.zip](https://github.com/chadvandy/cbfm_wh3/files/11682311/Cult.of.Sotek_Quick.Save.72207066769.zip)

**Additional context**
This has happened across multiple campaigns, but I just found this mod so I started this new one hoping it would be fixed. I can find other save files with this problem running vanilla if it would help. 

see comments

**Comment by Drazhir2** [comment]
I could not reproduce this, tested 2 vanilla campaigns, one I beelined for Sentinel of Time, the other Southern Sentinels.
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/fa4b1d03-0590-4e51-9c95-7b40c596376d)

If you upload a new save with the issue can you save before taking the settlement? that way we can load that save and test instead of only seeing the aftermath.

Also please make it a proper vanilla save.
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/c5e581fa-0ec9-407e-be69-3259c3b8251f)

**Comment by EnderBen** [comment]
Okay, very interesting. I just played a new vanilla Tehenhauin campaign and did the same thing with no bug. I autoresolved and got Sentinel of time on turn 6. No bug. So I loaded an autosave from turn 6 (so I could manually fight a battle and not lose all my units) and the bug popped up. So I loaded autosave turn 5, bug still there. Went all the way back to load autosave turn 2, bug still there. So I think its related to loading saves, as opposed to capturing the settlement. 

![20230608123925_1](https://github.com/chadvandy/cbfm_wh3/assets/115371548/ff467bf1-20bf-421c-892d-2676690b158e)


All my saves:
[Cult of Sotek_Auto-save.64279307024 (3).zip](https://github.com/chadvandy/cbfm_wh3/files/11692325/Cult.of.Sotek_Auto-save.64279307024.3.zip)
[Cult of Sotek_Auto-save.44279307024.zip](https://github.com/chadvandy/cbfm_wh3/files/11692330/Cult.of.Sotek_Auto-save.44279307024.zip)
[Cult of Sotek_Auto-save.34279307024.zip](https://github.com/chadvandy/cbfm_wh3/files/11692334/Cult.of.Sotek_Auto-save.34279307024.zip)

**Comment by Drazhir2** [comment]
Interesting indeed, This can be reproduced. 

I loaded a Turn 1 save, pressed End Turn and tadaaaaa 92!
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/4cb141f9-1526-4af3-8e91-57a738ce4408)

**Comment by EnderBen** [comment]
Great, my first bug report actually worked! Do I need to change the label or is that for someone with elevated rights that knows what their doing?

**Comment by Harmandodelavega** [comment]
presumably fixed by CA

from "for i = 1, #skaven_faction_list do							
		cm:apply_effect_bundle("wh2_dlc12_prophecy_of_sotek_stage_2_skaven", skaven_faction_list[i], -1)" to
"for i = 1, #skaven_faction_list do"

in tehenhauin lua

**Comment by Drazhir2** [comment]
That script change has no impact on this issue which affects more than our little lizard friend: https://community.creative-assembly.com/total-war/total-war-warhammer/forums/13-report-a-warhammer-iii-bug/threads/60-known-issue-control-x-provinces-quests-complete-erroneously (that's my report but I've seen plenty of others with other LLs too)

**Comment by Grimmys** [comment]
Was going to raise a new issue, but I see mine is probably connected so I will just sum up what happened to me during my Sotek campaign here:

After winning the "Plaque of Sotek" battle, I got accomplishment on two objectives for Stage 2 of _Prophecy of Sotek_:

- Own the entirety of 3 provinces (tells me my current is 6, while it's 2)
- Construct Blood Shrines of Sotek (while I still don't have the building in any of my few settlements)

Also, another weird thing: for the provinces objective for Stage 1, it's telling my current number of provinces is 4... Obviously it cannot be both 4 and 6 at the mean time (and anyway, it's neither of them), so maybe it's just... Twice the amount required for the objective ?
Doesn't match with one of the screenshots of Drazhir though, where it is suddenly 92. 

Oh also I'm on turn 18, and didn't face this issue any time earlier despite making a lot of battles...

![image](https://github.com/chadvandy/cbfm_wh3/assets/25286578/793f8243-b9f4-4a5b-9102-a6de41d8807c)
![image](https://github.com/chadvandy/cbfm_wh3/assets/25286578/a355c88e-a7a9-4778-b0fc-0c995de4977b)
