### ISSUE TITLE
Gotrek/Felix items are not removed when they leave + items duplicate when they die (Mixu)

### ISSUE THREAD

**Issue by Drazhir2** [chadvandy/cbfm_wh3#1276]
Seems like Gotrek's and Felix's items aren't removed when they leave your faction and getting Gotrek killed duplicates his axe
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/792d7a2c-ac08-4eff-902d-0200d53c0ada)

1. kill_gotrek_and_felix_characters function needs a cm:force_remove_ancillary_from_faction call for their items, so that those items will begone from your faction when they depart

2. to avoid duplicates rewrite the gotrek_or_felix_created listener to check if the ancillary is already present before using force_add_ancillary.

**Comment by Drazhir2** [comment]
The variables in the original script are all local, I'm afraid we're gonna have to overwrite the whole script.

**Comment by mfvreeland** [comment]
> The variables in the original script are all local, I'm afraid we're gonna have to overwrite the whole script.

The primary "gotrek_details" variable gets stored as a saved value, so it should be accessible from anywhere using the saved value function.

**Comment by Drazhir2** [comment]
yes but it's using other local variables, example from kill_gotrek_and_felix_characters:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/c8155a11-2c59-4d78-982e-091c123e3a0f)

**Comment by mfvreeland** [comment]
I haven't tested it, but this should solve the local variables problem without requiring a full function rewrite.
[zzz_cbfm_gotrek_felix_items.lua.txt](https://github.com/chadvandy/cbfm_wh3/files/12541045/zzz_cbfm_gotrek_felix_items.lua.txt)

**Comment by Drazhir2** [comment]
This won't work in my opinion.

Your gotrek_details is getting initialized once during load however kill_gotrek_and_felix_characters can be called anytime after loading a game so X turns later the gotrek_details from the fix would be way out-of-date. 

Even during the same turn it could go out of sync if updates are done to the original gotrek_details before calling kill_gotrek_and_felix_characters as the saved_value is only getting updated when the game saves.

**Comment by mfvreeland** [comment]
Yeah, good point. I'll have to give this a second look. I'm determined to solve this puzzle without a full rewrite.

**Comment by mfvreeland** [comment]
New solution for this problem submitted to the next test branch. This version hijacks a different function from the Gotrek and Felix script, `trigger_gotrek_and_felix_cutscene`, which does not use any of the local variables from elsewhere in the script. I can only remove the ancillaries on departure using this method -- it does not check for the ancillaries on return -- but this shouldn't matter as long as they are reliably removed when necessary. Feel free to test if you have G&F in your games.

**Comment by Drazhir2** [comment]
Nice sneaky trick, ran a quick test and it doesn't solve the issue when they get killed in battle (I would guess it does solve the issue if they get killed by the script but haven't tested it).

I ran a FactionTurnStart listener on the side counting their items, they spawned turn 6 and got killed turn 7:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/d7d2c48a-246c-44c4-99e2-bbe6d774de9b)
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/36fc767d-3d1a-47ab-810c-96bf8b56a2d6)

**Comment by mfvreeland** [comment]
I have only tested it when they leave via script, and it does work there, but I was worried it might not if they get killed "for real." I am curious if this applies only to the AI or not, though. If they are killed while part of a player faction, does the "departing" cutscene still play? If so, I think this fix _should_ still work. The AI may still keep duplicate weapons, but the player will never see that, and it won't affect anything because these are unique items that can only be equipped by Gotrek and Felix.

**Comment by Drazhir2** [comment]
I was playing Franz so it applies to the player for sure. I actually can't recall now if the departure cutscene played but looking at the script it cannot have played as they are not departing from the gotrek_FactionBeginTurnPhaseNormal listener, they are just wounded in battle and will be back in a few turns.

Just thinking about it couldn't we just write a simple CharacterConvalescedOrKilled listener for that case?

**Comment by Drazhir2** [comment]
Confirmed, I loaded my previous turn 7 save with both your fix and half of mine, got them both killed and pressed end-turn:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/ff54c61c-60ae-4f89-beb2-3b776f5f8c79)

**Comment by mfvreeland** [comment]
Won't we still run into the `gotrek_details` issue with this? It's being used in this listener, but it isn't defined anywhere.

**Comment by Drazhir2** [comment]
You're right, I'm dumb today, there was a big fat one in the debug :)

**Comment by mfvreeland** [comment]
Perhaps we could just create a "CharacterConvalescedOrKilled" listener for each of them that removes the ancillary whenever they die. This would be far simpler than anything we've tried yet, but it might just work in every scenario.

**Comment by Drazhir2** [comment]
Haha that's what I suggested before I edited to the dumb comment. However I think we need to keep your solution for when they leave through the script, and simply run the listener on Gotrek's death. Only the axe gets duplicated on death so if we run the listener on Felix too we'll remove the only sword.

```
core:add_listener(
	"cbfm_gotrek_killed",
	"CharacterConvalescedOrKilled",
	function(context)
		return context:character():character_subtype_key() == "wh2_pro08_neu_gotrek"
	end,
	function(context)
		local faction = context:character():faction()
		cm:force_remove_ancillary_from_faction(faction,"wh2_pro08_anc_weapon_gotrek_axe")
	end,
	true
)
```

I just tested it on my save, it worked fine (and no script error this time):
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/b1648e1e-a352-4a61-ac90-1654c728430f)
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/b8371c9a-8a3c-436f-a6a0-1f3c55e44a0d)

**Comment by Drazhir2** [comment]
And this is the root cause of the duplication bug, somehow the game fires both a CharacterConvalescedOrKilled and a CharacterCreated event at the same time when a lord dies:
![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/99aed1d6-eb26-4b1d-9a40-0fb51ea3cf44)

**Comment by mfvreeland** [comment]
That _is_ interesting, but I think all characters do that when wounded because the character gets "re-created" as injured (cqi changes). After looking more closely, I believe this may be the culprit in this case:

![image](https://github.com/chadvandy/cbfm_wh3/assets/112144702/ca02f763-6d02-4641-8d99-a2d72b7fef99)

In any case, I think your combined solution is the answer @Drazhir2. I'll add a new commit to the test branch.

**Comment by mfvreeland** [comment]
This was a fun exercise.
