### ISSUE TITLE
Ranged units standing still & not shooting - allegedly they are "moving fast".

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#533]
**Describe the bug**
Started a brand new campaign with Orion and later another with Sisters.
Ranged units will OFTEN after being told to move/turn simply stop shooting indefinitely, since the game seems to think they are still "moving fast" (running).
Only way to fix this is to notice which unit is bugged and tell it to move again - repeat process until the unit starts shooting again.
Units have "shoot at will" mode enabled, skirmish disabled and guard mode on (perhaps happens with guard mode off as well).
They are not in a formation and there are plenty of enemies in front of them (archers so no line of sight problems).
These bugged ranged units will literally stay inactive for the rest of the battle (unless moved again), i tested it by leaving several such bugged archers spend the whole battle in "moving fast" while plenty of enemies are available - they do not spend ammo and do not shoot (no kill nor damage once they get bugged).

**Expected behavior**
Shooters not getting stuck in "moving fast" mode after being moved, despite now being stationary and able to shoot at will

**To Reproduce**
1. Play as Orion or Sisters (perhaps affects other factions/races)
2. Enter any battle
3. Move your archers (in this screenshot it was glade guards but also happens with deepwood scouts)
4. Notice some of your archers will eventually stay in "moving fast" mode despite standing still, and will be unable to shoot until you try moving them again.

**Screenshots**
![image](https://user-images.githubusercontent.com/55892027/198880985-f494e2a4-6768-42e1-9306-b04ac2dc44f1.png)

**Additional context**
I do not know how "shoot while moving" and "360 degrees arc of fire" interacts with this bug.
I noticed this bug occurring very commonly with Glade guards.
Not sure is it related to maps or is it a bug available on any campaign manual battle map.

**Comment by Belphegor9527** [comment]
Hi, I notice this BUG too. It is BUG! you can check the archer when they r in that situation. u can see few of them just keep moving around( but they already on their position). Because of this BUG. I don't play woodelf now.
![QQ图片20221102012724](https://user-images.githubusercontent.com/117192187/199271809-072a28bb-d23d-4382-8105-102c8e0d048f.png)

**Comment by ebbitten** [comment]
I've also run into this issue, predominantly with my Orion campaign but I think i've seen it in others as well.

**Comment by trittimo** [comment]
I hate this bug so much. It ruins ranged units for me. I have no idea if this is something that can even be fixed via tables or if it's something wrong with the engine itself.

**Comment by Bogdanov89** [comment]
I recently did a campaign with Alith Anar and this issue is rampant with his two unique shadow archers.

Perhaps the issue is more prevalent with archers that can fire on the move, or fire in 360 degrees around themselves?...

**Comment by Belphegor9527** [comment]
I think this issue is more prevalent with ranged units that can fire on the move（I checked all of the units that can fire on the move…most infantry units have the same issue. For example the handgun unit for the empior）

发自我的iPhone

在 2023年3月6日，上午7:27，Bogdanov89 ***@***.***> 写道：

﻿

I recently did a campaign with Alith Anar and this issue is rampant with his two unique shadow archers.

Perhaps the issue is more prevalent with archers that can fire on the move, or fire in 360 degrees around themselves?...

**Comment by Bogdanov89** [comment]
There is a thread on CA bug forums where CA has replied and marked it with KNOWN ISSUE.
I believe its the same problem as the one reported in this github.
https://forums.totalwar.com/discussion/327847/warhammer-3-ranged-units-refuse-to-shoot

**Comment by mfvreeland** [comment]
CA improved this situation in 3.1, but it's still not perfect. Mods can't really affect it regardless.
